import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

// Ionic Components - Common UI Elements
import {
  IonApp,
  IonRouterOutlet,
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonButtons,
  IonButton,
  IonBackButton,
  IonMenuButton,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonInput,
  IonTextarea,
  IonSelect,
  IonSelectOption,
  IonCheckbox,
  IonRadio,
  IonRadioGroup,
  IonToggle,
  IonRange,
  IonSearchbar,
  IonSegment,
  IonSegmentButton,
  IonText,
  IonNote,
  IonBadge,
  IonChip,
  IonAvatar,
  IonThumbnail,
  IonImg,
  IonSpinner,
  IonProgressBar,
  IonToast,
  IonAlert,
  IonActionSheet,
  IonModal,
  IonPopover,
  IonLoading,
  IonPicker,
  IonDatetime,
  IonAccordion,
  IonAccordionGroup,
  IonBreadcrumb,
  IonBreadcrumbs,
  IonFab,
  IonFabButton,
  IonFabList,
  IonGrid,
  IonRow,
  IonCol,
  IonInfiniteScroll,
  IonInfiniteScrollContent,
  IonRefresher,
  IonRefresherContent,
  IonReorder,
  IonReorderGroup,
  IonTabs,
  IonTabBar,
  IonTab,
  IonTabButton,
  IonMenu,
  IonMenuToggle,
  IonSplitPane,
} from '@ionic/angular/standalone';

// Common imports for all pages
export const SHARED_IMPORTS = [
  CommonModule,
  FormsModule,
  ReactiveFormsModule,
  RouterModule,
  
  // Core Ionic Components
  IonApp,
  IonRouterOutlet,
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonButtons,
  IonButton,
  IonBackButton,
  IonMenuButton,
  IonIcon,
  
  // Form & List Components
  IonItem,
  IonLabel,
  IonList,
  IonInput,
  IonTextarea,
  IonSelect,
  IonSelectOption,
  IonCheckbox,
  IonRadio,
  IonRadioGroup,
  IonToggle,
  IonRange,
  IonSearchbar,
  
  // Card Components
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  
  // Display Components
  IonText,
  IonNote,
  IonBadge,
  IonChip,
  IonAvatar,
  IonThumbnail,
  IonImg,
  
  // Feedback Components
  IonSpinner,
  IonProgressBar,
  IonToast,
  IonAlert,
  IonActionSheet,
  IonModal,
  IonPopover,
  IonLoading,
  
  // Layout Components
  IonGrid,
  IonRow,
  IonCol,
  IonMenu,
  IonMenuToggle,
  IonSplitPane,
  
  // Navigation Components
  IonSegment,
  IonSegmentButton,
  IonTabs,
  IonTabBar,
  IonTab,
  IonTabButton,
] as const;

// Imports for pages that need advanced features
export const ADVANCED_IMPORTS = [
  IonPicker,
  IonDatetime,
  IonAccordion,
  IonAccordionGroup,
  IonBreadcrumb,
  IonBreadcrumbs,
  IonFab,
  IonFabButton,
  IonFabList,
  IonInfiniteScroll,
  IonInfiniteScrollContent,
  IonRefresher,
  IonRefresherContent,
  IonReorder,
  IonReorderGroup,
] as const;